### PR TITLE
Convert error page to Fomantic UI

### LINKED ISSUE #2887: Update exception page to Fomantic UI
Currently the exception page is made with bootstrap, primarily because it's from the era of the old default template. 

Updating it to fomantic ui will make it more consistent with defaultrevamp, and remove the need for the bootstrap dependency

### PR DESCRIPTION
**Pull request by tadhgboyle**
image

Screen Shot 2022-08-14 at 13 38 45

### CODE REVIEW

**Review by PadowYT2 — CHANGES_REQUESTED** [review]
Looks nice, maybe make the debug link a little higher, so it doesn't take its own space?

File: core/classes/Misc/ErrorHandler.php [hunk 1]
```diff
@@ -126,8 +128,8 @@ public static function catchException(?Throwable $exception, ?string $error_stri
             'LANG_CHARSET' => defined('LANG_CHARSET') ? LANG_CHARSET : 'utf-8',
             'TITLE' => $language->get('errors', 'fatal_error') . ' - ' . $site_name,
             'SITE_NAME' => $site_name,
-            'BOOTSTRAP' => $path . 'vendor/bootstrap/dist/css/bootstrap.min.css',
-            'BOOTSTRAP_JS' => $path . 'vendor/bootstrap/dist/js/bootstrap.min.js',
+            'SEMANTIC_JS' => '/custom/templates/DefaultRevamp/js/fomantic.min.js',
```
Comment (samerton) [inline core/classes/Misc/ErrorHandler.php]: Might be worth considering adding fomantic elsewhere in case the default revamp template is deleted

File: core/includes/error.tpl [hunk 2]
```diff
@@ -0,0 +1,351 @@
...
+
+        {/if}
+
+    </div>
+
+    {if $CAN_GENERATE_DEBUG}
+        <div class="ui modal tiny" id="debug_link_modal">
+            <i class="close icon"></i>
+            <div class="header">
+                Generate a debug link
```
Comment (samerton) [inline core/includes/error.tpl]: Should we be looking to translate all terms in this file? Maybe in the future?

Comment (tadhgboyle) [reply core/includes/error.tpl]: Good catch

**Review by PadowYT2 — DISMISSED** [review]

**Review by partydragen — APPROVED** [review]
