### PR TITLE
Make sure if installation is not finished

### LINKED ISSUE #3294: Website is available when installation is not finished
### Describe the issue

You could not finish the install but still visit the website kinda broken

### NamelessMC Version

Development version

### To Reproduce

_No response_

### Expected Behaviour

It should redirect to /install.php

### Screenshots

_No response_

### Additional Information

We should fix it for 2.1!

### PR DESCRIPTION
**Pull request by PadowYT2**
Closes #3294

### CODE REVIEW

File: index.php [hunk 1]
```diff
@@ -52,7 +52,7 @@
     die();
 }
 
-if (!Config::exists()) {
+if (!isset($CONFIG['installed']) || !Config::exists() && Config::get('core.installed') !== true) {
```
Comment (supercrafter100) [inline index.php]: What is the point of the first $CONFIG variable?

**Review by supercrafter100 — APPROVED** [review]
